/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GoHome: typeof import('./src/components/Homeviem/goHome.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
