/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddComBtn: typeof import('./src/components/commod-viem/addComBtn.vue')['default']
    Addcommodfrom: typeof import('./src/components/commod-viem/Comminfo/addcommodfrom.vue')['default']
    Comcard: typeof import('./src/components/mainviem/Home-view/comcard.vue')['default']
    Commod: typeof import('./src/components/commod-viem/commod.vue')['default']
    Commodinfo: typeof import('./src/components/commodinfo.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    Gocom: typeof import('./src/components/Homeviem/gocom.vue')['default']
    Godead: typeof import('./src/components/Homeviem/godead.vue')['default']
    GoHome: typeof import('./src/components/Homeviem/goHome.vue')['default']
    Goliem: typeof import('./src/components/Homeviem/goliem.vue')['default']
    Goseach: typeof import('./src/components/Homeviem/goseach.vue')['default']
    HelloWorld: typeof import('./src/components/mainviem/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    ItemViem: typeof import('./src/components/item-viem/item-viem.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    New_file: typeof import('./src/components/Homeviem/new_file.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seach: typeof import('./src/components/seach-viem/seach.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Swipe: typeof import('./src/components/mainviem/Home-view/swipe.vue')['default']
  }
}
